/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

CREATE DATABASE IF NOT EXISTS `bd_equipos` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci */;
USE `bd_equipos`;

CREATE TABLE IF NOT EXISTS `equipos` (
  `id_equipo` bigint(20) NOT NULL AUTO_INCREMENT,
  `dt_equipo` varchar(255) COLLATE utf8mb4_spanish_ci DEFAULT NULL,
  `nombre_equipo` varchar(255) COLLATE utf8mb4_spanish_ci DEFAULT NULL,
  `partidos_jugados` int(11) DEFAULT NULL,
  `puntos` int(11) DEFAULT NULL,
  `suplentes` int(11) DEFAULT NULL,
  `titulares` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_equipo`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_spanish_ci;

/*!40000 ALTER TABLE `equipos` DISABLE KEYS */;
INSERT INTO `equipos` (`id_equipo`, `dt_equipo`, `nombre_equipo`, `partidos_jugados`, `puntos`, `suplentes`, `titulares`) VALUES
	(1, 'MARECELO GALLARDO', 'RIVER PLATE', 13, 33, 22, 11),
	(2, 'GUILLERMO FARRÉ', 'BELGRANO', 13, 27, 12, 11),
	(3, 'JORGE ALMIRÓN', 'BOCA JUNIORS', 13, 24, 12, 11),
	(4, 'FERNANDO GAGO', 'RACING CLUB', 13, 24, 12, 11),
	(5, 'JULIO VACCARI', 'DEFENSA Y JUSTICIA', 14, 24, 12, 11),
	(6, 'EDUARDO DOMÍNGUEZ', 'ESTUDIANTES', 13, 23, 12, 11),
	(7, 'DIEGO MARTÍNEZ', 'TIGRE', 13, 22, 12, 11),
	(8, 'GABRIEL MILITO', 'AREGNTINOS JUNIORS', 13, 21, 12, 11),
	(9, 'RUBÉN DARÍO INSÚA', 'SAN LORENZO', 14, 21, 12, 11),
	(10, 'JAVIER GANDOLFI', 'TALLERES', 13, 19, 12, 11);
/*!40000 ALTER TABLE `equipos` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
